### PR TITLE
Thor fix encoding

### PR DESCRIPTION
**Pull request by wikfeldt**
new pull request since the one from thor-rvk should have been split up into three commits, and i shouldn't file pull requests when tired in the evenings...

@bast  asked on steps to reproduce the problem:
- on current master branch I get with Python2:
```
$ make -f Makefile_all
  File "source/wordcount.py", line 11, in load_text
    with open(filename, "r", encoding="utf-8") as input_fd:
TypeError: 'encoding' is an invalid keyword argument for this function
make: *** [processed_data/abyss.dat] Error 1
```
- replacing `open(filename, encoding="utf-8")` with `io.open(filename, encoding="utf-8")` solves this problem since it works with py2 and py3. After replacing with `io.open`, the next problem is:
```
$ make -f Makefile_all
  File "source/wordcount.py", line 24, in save_word_counts
    output.write("%s\n" % " ".join(str(c) for c in count))
TypeError: write() argument 1 must be unicode, not str
make: *** [processed_data/abyss.dat] Error 1
```
- this is partly fixed by making the string passed to write unicode: `output.write(u"%s\n" % " ".join(str(c) for c in count))` (using `u"string"`), but it still gets stuck on the `last.txt` datafile:
```
$ make -f Makefile_all
  File "source/wordcount.py", line 24, in <genexpr>
    output.write(u"%s\n" % " ".join(str(c) for c in count))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 3: ordinal not in range(128)
make: *** [processed_data/last.dat] Error 1
```

- in this PR I just ignore the non-ascii characters:
```
try:
    output.write(u"%s\n" % " ".join(str(c) for c in count))
except UnicodeEncodeError:
    pass #FIXME
```

### CODE REVIEW

**Comment by wikfeldt** [comment]
any ideas for practical solutions to this?

**Comment by bast** [comment]
Thanks! I will try to reproduce and check whether I can come up with something more robust but if no, then I will merge.

**Comment by bast** [comment]
I seem to have a much simpler solution by simply removing the `encoding="utf-8"` it works on my computer but maybe I am missing something. I will file another PR, you can test that one. Until then we can keep this one open.

**Comment by bast** [comment]
Please test #5 on your side.

**Comment by wikfeldt** [comment]
simpler and better solution in #5 , closing this one

**Pull request closed without merging**
